### ISSUE TITLE
Should mentions be tied to pings_open?

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#222]
Right now, we are tying the receipt of webmentions to the ping_status field in wp_post.

For one, it means that enabling webmentions means enabling pingbacks and trackbacks.

Want to contemplate the issue of whether or not  we should have our own field for this that would be set only if webmentions are disabled for a post.

That merged with the existing webmention support feature by post type... with new setting in the awaiting PR, would allow complete disconnection from the pingback and trackback configuration.

**Comment by pfefferle** [comment]
We can add a separate setting for Webmentions, but then it has to be Gutenberg compatible!

**Comment by janboddez** [comment]
I'm running into this also. I implemented some of Webmention into a different (IndieBlocks ...) plugin and don't do any ping or trackback support checking. I just look at whether comments are open.

I'm now trying to make my plugins more compatible with the Webmention plugin. But this is something that seems to come back. Why tie webmention support to trackback support? Can't you just say, "If webmentions are enabled for this post type, and this particular post accepts comments, then that's enough"? (I guess this comes down to moving from "pings open" to "comments open.")

**Comment by dshanske** [comment]
That's exactly what I was contemplating with this... although it does lose the opportunity to manually disable Webmentions on a single post.

**Comment by janboddez** [comment]
Ah, that's true! If you wanted to accept _only_ regular comments but not webmentions ...

A meta box + post meta would probably work for this sort of thing, also in Gutenberg. Because it's OK if the meta field gets saved "a tiny bit late." (Gutenberg does behave a bit weird when it comes to "old style" meta boxes/custom fields, in a race-condition-sort-of-way. Probably not a problem _in this particular case_.)

**Comment by dshanske** [comment]
I think I'm ready to start working on this in a few intermediate steps. Related, #425 and #235

1. Replace all calls to pings_open with a new function that initially can just call pings_open
2. Assume that anyone installing the webmention plugin wants webmentions open by default, again, we still have the disable by post type settings.
3. Register a new meta field that, if it exists and is true, then it will reject webmentions.
4. Amend the new function to pull from the field, but fallback to true.
5. Use a meta box for Classic. And we can always add a setting in the Block Editor if someone is willing to add the code in future.

@pfefferle and co...what do you think?

**Comment by MatzeKitt** [comment]
Since currently the default is still (even if filterable) that webmentions are tied to pingbacks/trackbacks, consider adding a notice in the Webmention settings if pingbacks/trackbacks are disabled in the discussion settings, as it’s highly likely that this produces a problem. I had this problem after enabling the plugin and needed to debug my path until I found the code where it’s checked for `pings_open`.
