### ISSUE TITLE
Remove webmention header if Pings closed

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#75]
If a page doesn't support pings/webmentions then the endpoint shouldn't be advertised on that page.

**Comment by dshanske** [comment]
https://github.com/Automattic/_s/pull/965

Further to this idea...it looks like themes are doing something similar for pings.

**Comment by pfefferle** [comment]
good point

**Comment by pfefferle** [comment]
done

**Comment by snarfed** [comment]
sounds like this was done but then later reverted? i'd like this. my use case is that i'm using "unlisted" posts to approximate private posts with better accessibility. background: https://indieweb.org/unlisted#Similarity_to_private_posts

i don't want to encourage or accept webmentions on these posts, so i'd like to turn off the webmention endpoint `<link>` tag and HTTP header. the posts are all in a specific category, so triggering on that would be an alternative, but i expect i can just disable pings on all posts in that category.

@dshanske shall we reopen this?

**Comment by dshanske** [comment]
Related #152

**Comment by dshanske** [comment]
I still can't remember what the problems were. @pfefferle Do you remember exactly what the issue was so I can try to address in a new option?

**Comment by dshanske** [comment]
We keep revisiting this conversation, but I keep forgetting to document it

**Comment by dshanske** [comment]
Merged in again. New implementation
